spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_db
    username: postgres
    password: tradewise321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: http://localhost:1234/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'go-selling'
    secret: 'mp3npE4H0LeAUn5LJWeFl7oQ55R6ypL0'
    provider: secret
file:
  uploadPath: shop-service/src/main/resources/storage/
openapi:
  service:
    title: shop-service
    version: 1.0.0
    url: http://localhost:1688

springdoc:
  api-docs:
    path: /shop-service/v3/api-docs
  swagger-ui:
    path: /shop-service/swagger-ui.html