spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: gosellingproject@gmail.com
    password: mmlrtnqtokjctfgx
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable : true
            required : true
          from: contact@email.com
      from:
        name: Sak
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: http://localhost:1234/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'go-selling'
    secret: '5C0KwGLLlVYFrap5mni59YnZOwoONS3t'
    provider: secret
logging:
  level:
    org.springframework.web: debug
openapi:
  service:
    title: user-service
    version: 1.0.0
    url: http://localhost:1688

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html