spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2005/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: http://localhost:1234/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'go-selling'
    secret: 'mp3npE4H0LeAUn5LJWeFl7oQ55R6ypL0'
    provider: secret
openapi:
  service:
    title: category-service
    version: 1.0.0
    url: http://localhost:1688

springdoc:
  api-docs:
    path: /category-service/v3/api-docs
  swagger-ui:
    path: /category-service/swagger-ui.html